### ISSUE TITLE
After shifting central/prime meridian, how to union together polygons along anti-meridian?

### ISSUE THREAD

**Issue by MartinBeal** [valentinitnelav/valentinitnelav.github.io#1]
I have used your code to re-center a world polygon data set to the Pacific Ocean (and it works great!), however I now have the problem that the polygons show a seam/split along the old anti-meridian, which after re-centering falls in the center of the map. 

I'm wondering if you have dealt with this issue yourself somehow? I posted a stack exchange question about it [here](https://gis.stackexchange.com/questions/332106/union-anti-meridian-multipolygons-after-re-centering-world-map) in case you would like to see more details. Thanks!

**Comment by valentinitnelav** [comment]
Hey @MartinBeal , 

I didn't have a look yet, but that is a very interesting question. Too bad that you didn't get yet an answer on gis.stackexchange . So far I am really booked and I didn't manage to make time to find a solution. Not sure when I'll actually be able to solve it.
The thing is that once I break the polygon structure to be able to plot with `ggplot2`, then you will most probably have to reconstruct the polygons (the hassle you asked to be avoided...)

Best,
Valentin

**Comment by MartinBeal** [comment]
@valentinitnelav here is a function which does the re-centering, and a simple dplyr::group_by() %>% summarise() to that deals with the line. 

https://github.com/AustralianAntarcticDivision/SOmap/issues/34#issuecomment-525734179
